name: Build & Test (Java 25 + Node 24)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # -------------------------------
      # Setup Java (Backend)
      # -------------------------------
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: maven

      # -------------------------------
      # Setup Node (Frontend)
      # -------------------------------
      - name: Set up Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: '24.2.0'
          cache: 'npm'
          cache-dependency-path: license-ui/package-lock.json

      # -------------------------------
      # Build Backend (REST API)
      # -------------------------------
      - name: Build REST API (rest-runner.jar)
        run: |
          mvn clean verify -Prest
          mv target/rest-runner.jar rest-runner.jar

      - name: Upload REST artifact
        uses: actions/upload-artifact@v4
        with:
          name: rest-runner
          path: rest-runner.jar

      # -------------------------------
      # Build Backend (Shell CLI)
      # -------------------------------
      - name: Build Shell CLI (shell-runner.jar)
        run: |
          mvn clean verify -Pshell
          mv target/shell-runner.jar shell-runner.jar

      - name: Upload Shell artifact
        uses: actions/upload-artifact@v4
        with:
          name: shell-runner
          path: shell-runner.jar

      # -------------------------------
      # Build Frontend (React/Vite)
      # -------------------------------
      - name: Install frontend deps
        working-directory: license-ui
        run: npm ci

      - name: Build frontend
        working-directory: license-ui
        run: npm run build

      - name: Upload Frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: license-ui/dist

